cmake_minimum_required(VERSION 4.0)
project(Learn_C_Clion C)

set(CMAKE_C_STANDARD 11)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_SOURCE_DIR}/bin/Debug)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_SOURCE_DIR}/bin/Release)


add_executable(Learn_C_Clion
        "ACM项目/Sand Castle S.cpp"
        作业/76-用对应字母替换掉字符串中的大写字母.c
        作业/75-统计一篇文章每行各类字符的个数.c
        作业/71-打印杨辉三角.c
        Day05/05-单个字符输入输出.cpp
        Day05/06-字符串函数.c
        Day05/07-枚举.c
        Day04/01-取地址.cpp
        Day04/03-指针使用.cpp
        Day04/04-指针&数组.cpp
        作业/77-改错求两数和.c
        作业/78-改错求最大值.c
        作业/79-改错求两整数阶乘之和.c
        作业/80-改错打印全局变量结果.c
        作业/81-打印1~n阶乘.c
        作业/82-用函数调用输出信息.c
        作业/83-求最大值函数.c
        作业/84-递归算法求年龄.c
        作业/85-递归求n阶乘.c
        作业/86-递归求Hanoi.c
        作业/87-求平均成绩.c
        作业/88-数组排序.c
        作业/89-求二维数组最大元素值.c
        Day02/01-循环.cpp
        Day02/02-数据类型.cpp
        Day01/04-循环.cpp
        Day01/03-条件判断.cpp
        Day01/02-表达式&赋值.cpp
        Day03/01-数组.cpp
        Day03/02-数组.cpp
        作业/90-编写判断素数函数.c
        作业/91-泰勒展开式求e近似值.c
        作业/92-求一批正整数的奇数和.c
        作业/93-分别逆向输出.c
        作业/94-菜单选择计算组合数或排列数.c
        作业/95-递归求兔子函数.c
        作业/96-函数求平均值.c
        作业/97-函数sort冒泡排序.c
        作业/67-重排整数各位数组成最大数和最小数.c
        作业/98-数组中查找指定元素.c
        作业/99-判断两个数组是否包含相同元素.c
        作业/100-编写函数求二维数组元素和.c
        作业/101-编写输入&排序&折半查找.c
        作业/66-求一组整数的最大值及其下标.c
        作业/102-定义函数strmcpy.c
        作业/103-删除字符串中相同字符.c
        Day04/07-动态内存分配.cpp
        Day04/06-指针运算.cpp
        Day04/05-指针&const.cpp
        Day04/02-指针.cpp
        Day03/03-二维数组.cpp
        Day01/01-变量&常量&浮点数.cpp
        Day05/01-字符串.cpp
        Day05/02-字符串常量.cpp
        Day05/03-字符串输入输出.cpp
        Day05/04-字符串数组.cpp
        作业/01-吃糖果.c
        作业/02-小鱼游泳.c
        作业/03-分割5位整数.c
        作业/04-计算表达式.c
        作业/05-利息.c
        作业/06-求和&乘积&平均数.c
        作业/07-圆柱体.c
        作业/08-求圆.c
        作业/09-能否被5整除.c
        作业/10-分段函数.c
        作业/11.1练习getchar.c
        作业/11.2-练习熟悉大小写字母ASCII.c
        作业/11-分段函数2.c
        作业/12-改错-乘除运算.c
        作业/13-改错-嵌套.c
        作业/14-改错-选择分段.c
        作业/15-判断整数.c
        作业/16-洛谷系统.c
        作业/17-3整数排序.c
        作业/18-判断回文数.c
        作业/19-判断三角形形状.c
        作业/20-计算分段函数.c
        作业/21-计算个人所得税.c
        作业/22-ISBN号码.c
        作业/23-显示某年某月的天数.c
        作业/24-改写if_else语句.c
        作业/25-改错-信息多次重复显示.c
        作业/26-改错-计算及格人数.c
        作业/27-改错-自由下落问题.c
        作业/28-改错-求平方和.c
        作业/29-改错-打印不超过100的圆面积.c
        作业/30-输入n求和.c
        作业/31-求个数&和&平均值.c
        作业/32-求π的近似值.c
        作业/33-兔子数列.c
        作业/34-判断是否为素数.c
        作业/35-破译密码.c
        作业/36-输入m&n递增&递减.c
        作业/37-猴子吃桃.c
        作业/38-辗转相除法求最大公约数.c
        作业/39-求一批正整数的奇数和.c
        作业/40-输出自然数和.c
        作业/41-计算分数和.c
        作业/42-求前n项和-分母3.c
        作业/43-100人民币换零.c
        作业/44-判断回文数.c
        作业/45-九九乘法表.c
        作业/46-求组合数.c
        作业/47-求aaan的和.c
        作业/48-统计各字符个数.c
        作业/49-柱状图打印.c
        作业/50-求班级平均分.c
        作业/51-求两整数间素数个数&和.c
        作业/52-求2~n的素数.c
        作业/53-找出给定正整数内的完数.c
        作业/54-冒泡排序.c
        作业/55-二维数组初始化数据.c
        作业/56-统计二维数组大于n的元素和.c
        作业/57-二维数组转置.c
        作业/58-二维数组求最大值.c
        作业/59-字符初始化.c
        作业/60-找三个字符串中的最大字符串.c
        作业/61-从长整数从高位分割.c
        作业/62-选择法排序.c
        作业/63-插入一个数到有序序列的正确位置.c
        作业/64-停车费问题.c
        作业/65-出现一次的数.c
        作业/68-最值&平均值&排序.c
        作业/69-求n阶方阵主对角线元素之和.c
        作业/70-判断是否为上三角矩阵.c
        作业/72-打印金字塔杨辉三角.c
        作业/73-查找二维数组的鞍点.c
        作业/74-输入两个不包含空格的字符串.c
        ACM项目/区间最大和.cpp
        ACM项目/双十一.cpp
        ACM项目/商店.cpp
        ACM项目/宝箱.cpp
        ACM项目/排列排序.cpp
        ACM项目/数对.cpp
        ACM项目/求区间和.cpp
        ACM项目/混合牛奶.cpp
        ACM项目/纪念品分组.cpp
        ACM项目/货仓选址.cpp
        ACM项目/陶陶摘苹果（升级版）.cpp
        "ACM项目/非常男女计划(error).cpp"
        Day04/08-结构体.cpp
        Day04/09-类型定义.c
        Day06/01-内存.cpp
        Day06/02-算法分析.cpp
        练习/06-水仙花数.cpp
        练习/07-九九乘法表.cpp
        练习/08-统计素数求和.cpp
        练习/05-素数数组.cpp
        练习/02-求平均数.cpp
        练习/01-猜拳游戏.cpp
        练习/03-整数求逆.cpp
        练习/04-求最大公约数.cpp
        作业/104-指针改错.c
        作业/105-指针改错-交换函数.c
        作业/106-指针变量访问整型变量.c
        作业/107-指针变量排序.c
        作业/108-指针变量-调用函数实现排序.c
        作业/109-指针改错-数组输入.c
        作业/110-指针引用数组.c
        作业/111-指针引用数组-逆序存.c
        作业/112-指针引用数组-列指针访问二维数组.c
        作业/113-指针引用数组-行指针访问二维数组.c
        作业/114-指针改错-字符串复制.c
        作业/115-指针引用字符串-字符串复制函数.c
        作业/116-指向函数指针-函数指针变量调用函数.c
        作业/117-返回指针函数-用指针函数输出指定序号学生成绩.c
        作业/118-指针数组-字母排序.c
        作业/119-动态内存分配-查不及格分数.c
        作业/120-指针-两数互换.c
        作业/121-指针-三个整数从大到小.c
        作业/122-指针-计算两数和与差.c
        作业/123-指针-数组元素位置互换.c
        作业/124-指针-插入数据.c
        作业/125-指针-约瑟夫环.c
        作业/126-指针-求二维数组和.c
        作业/127-指针-统计成绩.c
        作业/128-指针-函数求字符串长度.c
        作业/129-指针-数组排序n个字符串.c
        作业/130-结构体-改错-结构体变量的使用.c
        作业/131-结构体-选举投票.c
        作业/132-结构体-按照成绩的高低顺序输出学生信息.c
        作业/133-结构体-改错-指向结构体的指针.c
        作业/134-结构体-指针变量访问结构体变量中的成员.c
        作业/135-结构体-指针变量访问结构体数组.c
        作业/136-结构体-指针变量作函数参数.c
        作业/137-结构体-改错-单向链表的建立和输出.c
        作业/138-结构体-静态链表的创建与访问.c
        作业/139-共用体-改错-变量的赋值.c
        作业/140-结构体-计算某日期在本年中是第几天.c
        作业/141-结构体-按语文成绩由高到低输出学生信息.c
        作业/142-结构体-推销员业绩统计.c
        作业/143-结构体-通讯录排序.c
        作业/144-结构体-学生记录排序.c
        作业/145-结构体-n个学生信息的处理.c
        作业/146-结构体-动态链表的创建和输出.c
        Day06/03-链表-头插法.cpp
        Day06/04-链表-尾插法.cpp
        Day06/05-链表-插入&删除&获取长度&释放链表.cpp
        作业/147-结构体-动态链表的创建和输出.c
        作业/148-结构体-动态链表结点的删除.c
        Day06/06-顺序表-增删改查.cpp
        Day06/07-顺序表-动态分配内存.cpp
        考试/01.c
        考试/02.c
        考试/03.c
        考试/04.c
        考试/05.c
        考试/06.c
        考试/07.c
        考试/08.c
        考试/09.c
        考试/10.c
        考试/11.c
        考试/12.c
        考试/13.c
        考试/14.c
        考试/15.c
        考试/16.c
        考试/17.c
        考试/18.c
        考试/19.c
        考试/20.c
        考试/21.c
        考试/22.c
        考试/23.c
        考试/24.c
        考试/25.c
        作业/149~157/149-文件合并.c
        作业/149~157/150-统计文件内单词、字符数.c
        作业/149~157/151-文本文件字符串的读写方式.c
        作业/149~157/152-二进制文件的读写.c
)
